name: Publish to GitHub Packages
on:
  release:
    types: [ created ] # creating release from repo will auto trigger the packaging
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Publish package
        run: gradle publish
        env:
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          AUTHOR: ${{ secrets.AUTHOR }}